var dot = module.exports = {};

/**
 * Converts a graph object into dot file format.
 * @param {!Object} graph The graph to convert.
 * @returns {!String} the dot output.
 */
dot.convert = function conver(graph) {
  // Graph definition.
  var lines = [];
  lines.push("/* Autogenerated dependency graph, do not edit. */");
  lines.push("digraph snowfox {");

  // Nodes definition.
  var nodes = Object.keys(graph.nodes);
  nodes.forEach(function(node_id) {
    var node = graph.nodes[node_id];
    lines.push(
      "  \"" + node_id + "\"" +
      " [color=\"" + node.colour + "\"" +
      ",label=\"" + node.label + "\"];"
    );
  });

  // Edges definition.
  lines.push("", "");
  graph.edges.forEach(function(edge) {
    lines.push(
      "  \"" + edge.from + "\" -> \"" +
      edge.to + "\" [color=\"" + edge.colour + "\"];"
    );
  });

  // Done.
  lines.push("}");
  return lines.join('\n');
};
