var assert = require("assert");
var mocha  = require("mocha");
var dot    = require("../../graph/dot");


suite("Graph", function() {
  suite("dot", function() {
    test("empty", function() {
      var graph = { edges: [], nodes: {} };
      var plot  = dot.convert(graph);
      assert.equal(plot, [
        "/* Autogenerated dependency graph, do not edit. */",
        "digraph snowfox {",
        "", "",
        "}"
      ].join('\n'));
    });

    test("node only", function() {
      var graph = {
        edges: [],
        nodes: {
          a: { colour: "#a", label: "a" }
        }
      };
      var plot  = dot.convert(graph);
      assert.equal(plot, [
        '/* Autogenerated dependency graph, do not edit. */',
        'digraph snowfox {',
        '  "a" [color="#a",label="a"];',
        '', '',
        '}'
      ].join('\n'));
    });

    test("nodes and edge", function() {
      var graph = {
        edges: [{
          from: "a",
          to:   "b",
          colour: "#b"
        }],
        nodes: {
          a: { colour: "#a", label: "a" },
          b: { colour: "#b", label: "b" }
        }
      };
      var plot  = dot.convert(graph);
      assert.equal(plot, [
        '/* Autogenerated dependency graph, do not edit. */',
        'digraph snowfox {',
        '  "a" [color="#a",label="a"];',
        '  "b" [color="#b",label="b"];',
        '', '',
        '  "a" -> "b" [color="#b"];',
        '}'
      ].join('\n'));
    });
  });
});
